PJ_SIM_SUNBNB_2023-15 [FE] Listing Item Component
framgia/pj_sim-sunbnb pull request #30
Opened 2023-08-09 06:50 UTC by LennardUy104

# Issue Link
https://framgiaph.backlog.com/view/PJ_SIM_SUNBNB_2023-15

# Definition of Done
* [x] Create Card component for all listings showing
    * [x] Picture of home
    * [x] Listing name
    * [x] Price - type - capacity
    * [x] Average Rating
    * [x] Number of Reviews

# Notes
Insert the component in the all component for checking

# Expected Output
![image](https://github.com/framgia/pj_sim-sunbnb/assets/137018413/02138aae-7f4a-4e79-b233-091a1931f555)

# Screenshots/Recordings
![image](https://github.com/framgia/pj_sim-sunbnb/assets/137018413/77d6a4d9-4655-4868-880f-e9445b4be974)

2023-08-09 07:58 UTC, andreenriquez11 requested changes

2023-08-09 07:58 UTC, andreenriquez11 commented on fe/src/utilities/dummy/ListingData.json
Can you add varieties to the list especially the name, image, type for a better view. Thanks

2023-08-09 10:22 UTC, andreenriquez11 requested changes

2023-08-09 10:22 UTC, andreenriquez11 commented on fe/src/utilities/dummy/ListingData.json
> +        "image": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBUVFBcVFRUYGBcZGhoZGhoaGhkiIB0aGRocGhkiICAgICwkHSMpIBkaJDYlKS4vMzMzGSI4PjgyPSwyMy8BCwsLDw4PHhISHTUpIiAyMjIyMjIyLzIyMjIyMj
why is this so long?

2023-08-09 10:22 UTC, andreenriquez11 commented on fe/src/components/ListingsList.vue
Remove extra spaces on the bottom

2023-08-09 10:30 UTC, LennardUy104 commented
@andreenriquez11 Resolve Changes already

2023-08-10 01:35 UTC, andreenriquez11 approved these changes
looks good to me, thanks

2023-08-15 02:26 UTC, roseaugusto requested changes

2023-08-15 02:26 UTC, roseaugusto commented on fe/src/components/ListingCard.vue
> +console.log(homeItem);
remove console

2023-08-15 02:45 UTC, merged