PJ_SIM_SUNBNB_2023-45 [BE] Vuetify and Router
framgia/pj_sim-sunbnb pull request #4
Opened 2023-07-20 03:52 UTC by andreenriquez11

# Issue Link
https://framgiaph.backlog.com/view/PJ_SIM_SUNBNB_2023-45

# Definition of Done
* [x] Update consolidate package
* [x] Install Vuetify 
* [x] Manually install router
* [x] Add pages folder

# Notes
n/a

# Screenshots/Recordings
n/a

2023-07-21 09:48 UTC, LennardUy104 requested changes
Please restore .env.example file

2023-07-21 09:48 UTC, LennardUy104 commented on fe/.env.example
Do not delete .env.example since we are using this to the secret keys of the application

2023-07-24 02:40 UTC, andreenriquez11 commented on fe/.env.example
Restored already @LennardUy104

2023-07-24 02:44 UTC, LennardUy104 commented on fe/.env.example
Nice! thanks

2023-07-25 03:12 UTC, roseaugusto approved these changes

2023-07-25 03:33 UTC, merged