PJ_SIM_SUNBNB_2023-5 [FE] Login
framgia/pj_sim-sunbnb pull request #9
Opened 2023-07-26 02:33 UTC by ThereseRoca

#  Issue Link
  [PJ_SIM_SUNBNB_2023-5 [FE] Login
](https://framgiaph.backlog.com/view/PJ_SIM_SUNBNB_2023-5)

#Definition of Done 
Create a markup for the login page with the components:

- [ ] Email Input Field
- [ ] Password Input Field
- [ ] Log In Button
- [ ] Input validations

# Note
installed vee-validate npm install vee-validate --save

# Screenshots
![image](https://github.com/framgia/pj_sim-sunbnb/assets/138637515/f0905e62-b8d0-4d85-9a96-4e826602c235)

2023-07-26 02:40 UTC, LennardUy104 commented on fe/src/pages/LogIn.vue
> +          if (value?.length >= 8 && /^(?=.*[A-Za-z])(?=.*\d).*$/.test(value)) return true
Please remove the validation of password and email

we will validate it once the user clicks login and then check if credentials are true if not we display "invalid email or password"

2023-07-26 02:40 UTC, LennardUy104 requested changes
Please remove validations. thanks!

2023-07-26 06:51 UTC, ThereseRoca commented
> Please remove validations. thanks!

Validations removed, thank you.

2023-07-27 01:47 UTC, LennardUy104 approved these changes
Looks Good, Nice

2023-07-28 05:50 UTC, roseaugusto requested changes

2023-07-28 05:50 UTC, roseaugusto commented on fe/src/pages/LogIn.vue
> +      //BE tasks
please put a TODO comment instead of unfinished code
`// this function will be used to trigger login functionality after BE implementation`

2023-07-28 05:50 UTC, roseaugusto commented on fe/src/router/index.js
> +    component: LogIn,
```suggestion
    component: Login,
```

2023-07-28 05:50 UTC, roseaugusto commented on fe/src/router/index.js
> +import LogIn from "../pages/LogIn.vue";
It's okay one word.

```suggestion
import Login from "../pages/Login.vue";
```

2023-07-31 09:32 UTC, ejanton-sun approved these changes
# Approved

2023-07-31 09:33 UTC, merged